spring:
  zipkin:
    base-url: http://localhost:9411
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      dll-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/university?createDatabaseIfNotExist=true
    username: root
    password: springbankRootPsw
  application:
    name: student-service

server:
  port: 8091

address:
  service:
    url: http://localhost:8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      addressService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 5
        allowHealthIndicatorToFail: true
        registerHealthIndicator: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# closed - UP
# open - DOWN
# half-open - UNKNOWN