server:
  port: 9092

axon:
  axonserver:
    servers: axon-server

spring:
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: bank
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      dll-auto: update
  datasource:
    url: jdbc:mysql://mysql-container:3306/bank?createDatabaseIfNotExist=true
    username: root
    password: springbankRootPsw

security:
  oauth2:
    resource:
      jwt:
        key-value: springbankSigningKey