server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/vsushko/workspace/java-projects/spring-boot-spring-cloud-microservices/university-app/local-repo/
          refreshRate: 5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
